name: 'oapi-codegen action'
author: 'Dummy'
description: 'oapi-codegen action'

branding:
  icon: 'file'
  color: 'gray-dark'
inputs:
    oapi:
        description: 'OpenAPI specfile'
        required: true
        default: 'openapi-spec.yaml'
    boilerplates:
        description: 'Boilerplates types'
        required: false
        default: "server,types,spec"
    package:
        description: 'Package name'
        required: false
        default: 'main'            
    export:
        description: 'Enable exporting to file'
        required: false
        default: true  
    export_filename:
        description: 'Export file name'
        required: false
        default: 'server.gen.go'                
runs:
    using: 'docker'
    image: 'Dockerfile'
