name: test
on: 
  push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run oapi-codegen
        uses: ./
        with:
          oapi: "openapi-spec.yaml"
          boilerplates: "server,types,spec"
          package: "api"
          export: true
          export_filename: "server.gen.go"
      - name: check the generated file
        run: |
          cat "server.gen.go"