name: test
on: 
  push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          filename: "openapi-spec.yaml"
          generate_types: "server,types,spec"
          package_name: "api"